export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST ";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS ";
export const GET_AUTH_FAILURE = "GET_AUTH_FAILURE ";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST ";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE ";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS ";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// fake

export const CONNECT_THE_USER = "CONNECT_THE_USER";
export const AUTH_THE_USER = "AUTH_THE_USER";
